name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Test Libro Service
      working-directory: ./libro-service
      run: mvn test
    
    - name: Build and Test Autor Service
      working-directory: ./autor-service
      run: mvn test
    
    - name: Build and Test Gateway Service
      working-directory: ./gateway-service
      run: mvn test
    
    - name: Build with Maven
      run: |
        cd libro-service && mvn -B package -DskipTests && cd ..
        cd autor-service && mvn -B package -DskipTests && cd ..
        cd gateway-service && mvn -B package -DskipTests && cd ..
